<?php
define('ROOT_URL','http://52.198.196.126/board/');
define('BASE_CONT','./controllers/BoardController.php');
define('DB_VENDOR','mysql');
define('DB_HOST','52.198.196.126');
define('DB_NAME','board');
define('DB_USER','root');
define('DB_PASS','ubuntu');
define('LOG_PATH','./logs/');
define('FILE_PATH','./files/');
?>