<?php
define('ROOT_URL','http://localhost/project/');
define('ROOT_DOC','project');
define('DB_VENDOR','mysql');
define('DB_HOST','52.198.196.126');
define('DB_NAME','board');
define('DB_USER','root');
define('DB_PASS','ubuntu');
define('LOG_PATH','./logs/');
define('FILE_PATH','./files/');
?>